java_binary(
    name = "CarapaceSpec",
    srcs = ["CarapaceSpec.java"],
    deps = [
        "//src/main/java/com/google/devtools/build/lib:runtime",
        "//src/main/java/com/google/devtools/build/lib/bazel:modules",
        "//src/main/java/com/google/devtools/build/lib/bazel/commands",
        "//src/main/java/com/google/devtools/build/lib/runtime/commands",
        "//src/main/java/com/google/devtools/common/options",
        "@maven//:org_yaml_snakeyaml",
    ],
)
